### PR TITLE
Encryption v2 and thread blocks v2

### LINKED ISSUE #84: Single-use encryption key for every photo / file
Flagging this here, @andrewxhill mentioned a protocol he came across that creates a keypair for each file and thought it could possibly solve some issues for us... what was is called?

### LINKED ISSUE #117: One mnemonic to rule them all
Currently, we have a key pair for each thread. We wouldn't want to have the user write down each one. For recovery, we can just make one master key which is used to encrypt all the others, which are then stored in a the user's wallet

### LINKED ISSUE #125: Break out photo data from update chain
Related to #84, a file should not have to be re-added / duplicated on IPFS for each thread it's in, meaning that it should be standalone / not part of an update chain.

### PR DESCRIPTION
**Pull request by sanderpick**
fixes #125 
fixes #117 
fixes #84

### CODE REVIEW

**Comment by sanderpick** [comment]
ugh, +2,921 −3,391 -- getting _real_ close here

**Comment by sanderpick** [comment]
Little more cleanup here, then tests.

**Comment by sanderpick** [comment]
Progress

screenshot 2018-06-08 19 25 52

**Comment by sanderpick** [comment]
Okay, merged - plenty left to do, but let's move to smaller PRs.

**Comment by andrewxhill** [comment]
goodbye albums. long live the wallet!

**Pull request merged**
