### PR TITLE
PubSub Contacts

### PR DESCRIPTION
**Pull request by sanderpick**
- Adds contact cafe-based publishing
- Adds contact search
- Removes profiles table (a peer has itself as a contact)
- Adds `Avatar` to `Contact`

```
Usage:
  textile [OPTIONS] contacts find

Find contact information.

Help Options:
  -h, --help             Show this help message

[find command options]
      -u, --username=    A username to use in the search.
      -p, --peer=        A Peer ID use in the search.
      -a, --address=     An account address to use in the search.
          --local        Only search local contacts.
          --limit=       Stops searching after limit results are found. (default: 5)
          --wait=        Stops searching after 'wait' seconds have elapsed. (default: 5)

    Client Options:
          --api=         API address to use (default: http://127.0.0.1:40600)
          --api-version= API version to use (default: v0)
```

TODO as a follow up:
- Match against peer id and address, in addition to username
- Remove dups in cafe and locally collected matches

### CODE REVIEW

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: cfe155b69984902a58f8a46929a3eb2d9c5f511b
  * Commits must be in the following format: **%{scope}: %{description}**



---
This message was auto-generated by https://gitcop.com

**Comment by sanderpick** [comment]
Mobile API changes:
- Removes `Profile` object (now just `repo.Contact`)
- Removes `PeerProfile` method
- Adds `Avatar` to `ContactInfo`
- Adds `Avatar` method
- Adds `FindContact` method

Larger changes
- We'll have to figure out how to deal with avatars again in a world without IPNS profiles. Since `Contact` and `ContactInfo` have the avatar's target hash on it, we could just use it with `TextileImage`, not caring if it's the own peer's or not.

**Comment by sanderpick** [comment]
Hmm, actually avatar handling isn't really any diff, since we can still use any gateway to (attempt to) display it. This diff is that now we'll have the actual IPFS hash (of the file target) instead of having to access it via IPNS at the peer's ID. For example, this is my local node's contact "card":

```
{
    "id": "12D3KooWHqceR5Be4UBTzfT9bRvopHND2XJ5Tah7VDeUin9YPgEK",
    "address": "P8X6AY7ScdVqNsVn1ThLY3rpZKvPccBZwsCHxf4Ha53sAkEm",
    "username": "sander",
    "avatar": "Qmbs6M5GNaVj6W2nJ7pUiPHSk5HvHZtWgEeEPSBU3uifF9",
    "inboxes": [
        {
            "peer": "12D3KooWHZ5djm2tmQoXU79BoTPPWJ845VDf1Tp9B3edWmuH4KRx",
            "address": "P4pMyHsf9ZhPEK7SiYXpj4WuTh43uvp25hBDpJVCVbMxAeEw",
            "api": "v0",
            "protocol": "/textile/cafe/1.0.0",
            "node": "1.0.0-rc24",
            "url": "http://127.0.0.1:41601",
            "swarm": [
                "/ip4/127.0.0.1/tcp/1670"
            ]
        }
    ],
    "added": "2019-01-10T20:04:15-08:00"
}
```

My avatar is available here:

```
http://127.0.0.1:5050/ipfs/Qmbs6M5GNaVj6W2nJ7pUiPHSk5HvHZtWgEeEPSBU3uifF9/0/small/d
```

or

```
https://gateway.textile.io/ipfs/Qmbs6M5GNaVj6W2nJ7pUiPHSk5HvHZtWgEeEPSBU3uifF9/0/small/d
```

or 

```
https://gateway.ipfs.io/ipfs/Qmbs6M5GNaVj6W2nJ7pUiPHSk5HvHZtWgEeEPSBU3uifF9/0/small/d
```

**Comment by sanderpick** [comment]
- [x] Match against peer id and address, in addition to username
- [x] Remove dups in results collected on host Cafe and locally collected matches from multiple Cafes, while keeping most recently updated results

**Comment by sanderpick** [comment]
Head up in case anyone wants to take a look at this... I'll probably merge this later tonight so I can update the mobile PR w/ a real framework build.

**Pull request merged**
