### PR TITLE
reproducible dependencies and build tooling

### PR DESCRIPTION
**Pull request by sanderpick**
pre-work before getting travis ci going. tried for awhile to get `gx` and `dep` (official golang pack manager) to play nice to no avail. for now, whenever you do a `dep ensure`, the local gx packages will be removed by `dep` from vendor folder because they are not managed by dep... talk of getting `dep` to read ipfs paths, so might just work in near future.

### CODE REVIEW

**Comment by sanderpick** [comment]
@asutula i refactored this to actually ignore everything, more like a nodejs project. so, the pr title is not accurate, but whatever. other stuff added in here:
- use npm for build setup / testing / versioning commands
- add husky for git hooks
- add commitizen for good looking and understandable commit messages

**Comment by sanderpick** [comment]
add lint script which doesn't fail the commit at the moment

**Comment by sanderpick** [comment]
testing slack one two one two

**Comment by sanderpick** [comment]
testing slack again one two one two

**Comment by asutula** [comment]
is this ready to go?

**Comment by sanderpick** [comment]
yeah

**Pull request merged**
